### ISSUE TITLE
No matching export

### ISSUE THREAD

**Issue by ic2301** [redotvideo/revideo#227]
New install on fedora 40.
Blank project (npm init)
On unning npm start get:

Error: Build failed with 2 errors:
node_modules/@revideo/core/lib/types/Color.js:1:9: ERROR: No matching export in "node_modules/chroma-js/index.js" for import "Color"
node_modules/@revideo/core/lib/types/Color.js:1:16: ERROR: No matching export in "node_modules/chroma-js/index.js" for import "mix"

**Comment by justusmattern27** [comment]
hey, thanks for reporting this! I've already responded to this in detail in #228, feel free to check out my response there. 

TLDR:
- this is caused by a newer version of chroma-js. To fix it, downgrade chroma-js to 2.4.x.
- our newest release (will release today) will include a fix (pinned version of chroma-js)

**Comment by hkonsti** [comment]
Thanks for reporting! We just released 0.5.3 which should fix this. Feel free to reopen in case you're still facing issues related to chroma-js after upgrading!
